# Configure CI
say "\n-- Configuring application for CI ...\n"

say "\n    Creating build.sh ...\n"

file 'build.sh', <<-RUBY.gsub(/^ {2}/, '')
  #!/bin/bash
  # Autogenerated F/ build script.  Tweak at will.
  # RVM
  source ~/.profile
  rvm use ree@#{app_name} --create
  export DISPLAY=:99

  # Stop old XVFBs
  start-stop-daemon --pidfile xvfb-x11vnc.pid --stop
  start-stop-daemon --pidfile xvfb.pid --stop

  # Start new XVFBs
  start-stop-daemon --pidfile xvfb.pid --make-pidfile --exec /usr/bin/Xvfb --background --start -- -ac :99
  start-stop-daemon --pidfile xvfb-x11vnc.pid --make-pidfile --exec /usr/bin/x11vnc --background --start -- -rfbport 5901 -display :99

  # Bundle
  gem install bundler -v 1.0.0 --no-ri --no-rdoc && \
  bundle install --deployment && \

  # DB Config
  cp config/database.example.yml config/database.yml && \
  bundle exec rake db:drop:all && \
  bundle exec rake db:create:all && \
  bundle exec rake db:migrate && \

  # Tests
  CUCUMBER_FORMAT=progress bundle exec rake && \
  bundle exec evergreen run && \
  bundle exec rake deploy:demo
  BUILD_STATUS=$?

  # Clean up XVFBs
  start-stop-daemon --pidfile xvfb-x11vnc.pid --stop
  start-stop-daemon --pidfile xvfb.pid --stop
  exit $BUILD_STATUS
RUBY

run "chmod +x build.sh"